### ISSUE TITLE
Create Complete CCA Attestation Token

### ISSUE THREAD

**Issue by yogeshbdeshpande** [veraison/ccatoken#3]
This issue tracks the generation of CCA Evidence (i.e Attestation Token) as listed in the section A7.2.3 of 
 [RMM Specification](https://developer.arm.com/documentation/den0137/a/?lang=en)

**Comment by yogeshbdeshpande** [comment]
This work will complete by 12/10/2022

**Comment by thomas-fossati** [comment]
> This work will complete by 12/10/2022

a way to do this would be to set a GitHub milestone.
